baseurl: https://azlinux.fr/
languageCode: fr-FR
theme: hugo-theme-stack
paginate: 50
title: azLinux
DefaultContentLanguage: fr
hasCJKLanguage: false
permalinks:
    post: /:slug/
    page: /:slug/
outputFormats:
    jsonfeed:
        mediaType: "application/json"
        baseName: "feed"
        isPlainText: true
params:
    author: baptiste
    description: Nous ne parlons pas seulement de Linux, mais aussi de nombreux sujets intéressants comme la sécurité, la protection des données, etc.
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: https://azlinux.fr/v1/images/77575/raw.png
    footer:
        since: 2022
        customText:
    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST
    sidebar:
        emoji:
        subtitle:
        avatar:
            enabled: true
            local: false
            src: https://azlinux.fr/v1/images/55898/raw.webp
    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: Licensed under CC BY-NC-SA 4.0
    comments:
        enabled: true
        provider: giscus
        giscus:
            repo: baptiste313/azlinux
            repoID: R_kgDOGwq8tw
            category: General
            categoryID: DIC_kwDOGwq8t84CA9fa
            mapping: title
            lightTheme: https://cdn.jsdelivr.net/gh/giscus/giscus/styles/themes/light.css
            darkTheme: https://cdn.jsdelivr.net/gh/giscus/giscus/styles/themes/dark_dimmed.css
            reactionsEnabled: 1
            emitMetadata: 0
    widgets:
        enabled:
            - search
            - archives
        archives:
            limit: 5

        tagCloud:
            limit: 10
    opengraph:
        twitter:
            site:
            card: summary_large_image
    defaultImage:
        opengraph:
            enabled: true
            local: false
            src: https://azlinux.fr/v1/images/93622/raw.webp
    colorScheme:
        toggle: true
        default: auto
    imageProcessing:
        cover:
            enabled: false
        content:
            enabled: false
menu:
    main:
        - identifier: home
          name: Accueil
          url: /
          weight: -100
          params:
              newTab: false
              icon: home
    social:
        - identifier: discord
          name: Discord
          url: https://discord.com/invite/aThsHpfa7J
          params:
            icon: brand-discord
        - identifier: rss
          name: RSS
          url: https://azlinux.fr/index.xml
          params:
            icon: rss
        - identifier: youtube
          name: YouTube
          url: https://www.youtube.com/channel/UCv1Dfrx1Z1sF94s-d7M92Bw?sub_confirmation=1
          params:
            icon: brand-youtube
        - identifier: github
          name: GitHub
          url: https://github.com/baptiste313/azlinux
          params:
            icon: brand-github
related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200
markup:
    goldmark:
        renderer:
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
